name: EmakiCoreLib
main: emaki.jiuwu.craft.corelib.EmakiCoreLibPlugin
version: ${project.version}
api-version: "1.21"
author: JiuWu
description: Shared native Java core library for Emaki plugins
softdepend:
  - Vault
  - ExcellentEconomy
  - PlaceholderAPI
  - MMOItems
  - MythicMobs
  - ItemsAdder
  - Nexo
  - NeigeItems
  - CraftEngine
