// EmakiCodex（原 EmakiCodex/pom.xml）。
version = '1.1.4'

dependencies {
    // 原 shade artifactSet 白名单。
    shadeBundle project(':EmakiCodexApi')

    // 原 compile 作用域。
    api project(':EmakiCoreLibApi')
    api project(':EmakiCoreLib')
    api project(':EmakiCodexApi')

    // 原 provided 作用域。
    provided project(':EmakiAttributeApi')
    provided libs.paper.api
    provided libs.graalvm.polyglot
    provided libs.placeholderapi
    provided libs.packetevents.spigot
    provided libs.adventure.text.serializer.gson
    provided libs.adventure.text.serializer.json

    // 原 test 作用域。
    testImplementation libs.junit.jupiter
    testImplementation project(':EmakiAttribute')
    testImplementation libs.boosted.yaml
    testImplementation libs.mockbukkit
}
