name: EmakiMobs
main: emaki.jiuwu.craft.mobs.EmakiMobsPlugin
version: ${project.version}
api-version: "1.21.8"
folia-supported: true
dependencies:
  server:
    EmakiCoreLib:
      load: BEFORE
      required: true
      join-classpath: true
    EmakiAttribute:
      load: BEFORE
      required: false
      join-classpath: true
    EmakiSkills:
      load: BEFORE
      required: false
      join-classpath: true
    EmakiItem:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
permissions:
  emakimobs.use:
    default: true
  emakimobs.spawn:
    default: op
  emakimobs.reload:
    default: op
  emakimobs.debug:
    default: op
  emakimobs.admin:
    default: op
