name: EmakiCodex
main: emaki.jiuwu.craft.codex.EmakiCodexPlugin
version: ${project.version}
api-version: "1.21"
folia-supported: true
depend:
  - EmakiCoreLib
softdepend:
  - PlaceholderAPI
  - packetevents
commands:
  codex:
    aliases: [ecodex]
    permission: emakicodex.use
permissions:
  emakicodex.use:
    default: true
  emakicodex.reload:
    default: op
  emakicodex.debug:
    default: op
  emakicodex.admin:
    default: op
