// EmakiCooking（原 EmakiCooking/pom.xml）。
version = '4.3.6'

dependencies {
    // 原 shade artifactSet 白名单。
    shadeBundle project(':EmakiCookingApi')

    // 原 compile 作用域。
    api project(':EmakiCoreLibApi')
    api project(':EmakiCoreLib')
    api project(':EmakiCookingApi')

    // 原 provided 作用域。
    provided libs.paper.api
    provided libs.placeholderapi
    provided libs.craft.engine.core
    provided libs.craft.engine.bukkit
    provided libs.itemsadder.api
    provided(libs.nexo) { transitive = false }
    provided(libs.oraxen) { transitive = false }
    provided libs.packetevents.spigot
    provided libs.mmoitems.api
    provided libs.mythiclib.dist
    provided libs.neigeitems

    // 原 test 作用域。
    testImplementation libs.junit.jupiter
    testImplementation libs.boosted.yaml
    testImplementation libs.mockbukkit
}
