name: EmakiItem
main: emaki.jiuwu.craft.item.EmakiItemPlugin
version: ${project.version}
api-version: "1.21"
folia-supported: true
depend:
  - EmakiCoreLib
softdepend:
  - EmakiAttribute
  - EmakiSkills
  - PlaceholderAPI
commands:
  emakiitem:
    aliases: [ei]
    permission: emakiitem.use
permissions:
  emakiitem.use:
    default: true
  emakiitem.give:
    default: op
  emakiitem.inspect:
    default: op
  emakiitem.update:
    default: op
  emakiitem.reload:
    default: op
  emakiitem.debug:
    default: op
  emakiitem.admin:
    default: op
