import { registerModuleLocale } from 'emaki-web-console';
import { EmakiGemItemSurface } from './EmakiGemItemSurface';
import { PluginGuiSurface } from './PluginGuiSurface';

registerModuleLocale('EmakiGem', 'zh-CN', {
  'emakigem.surface.gem': '宝石定义',
  'emakigem.surface.socketItem': '宝石插槽物品',
  'emakigem.surface.gui': '宝石 GUI',
  'emakigem.preview.aria': '宝石物品预览',
  'emakigem.preview.kind.gem': '宝石',
  'emakigem.preview.kind.socket': '插槽物品',
  'emakigem.preview.kind.generic': '物品',
  'emakigem.preview.levelTitle': '升级等级预览',
  'emakigem.preview.levelHint': '切换等级会用当前草稿重新生成 Lore 与效果。',
  'emakigem.preview.levelCurrent': '当前 Lv.{level}',
  'emakigem.preview.levelBase': '基础等级',
  'emakigem.preview.status.syncing': '同步中',
  'emakigem.preview.status.live': '实时',
  'emakigem.preview.status.failed': '预览失败',
  'emakigem.preview.empty': '暂无预览',
  'emakigem.section.basic': '基础字段',
  'emakigem.section.effects': 'effects 效果',
  'emakigem.section.legacy': '兼容旧字段',
  'emakigem.section.costReturn': '费用与返还',
  'emakigem.section.upgrade': 'upgrade 升级配置',
  'emakigem.section.gemActions': '宝石动作',
  'emakigem.section.levels': '升级等级',
  'emakigem.section.levelEffects': '等级效果',
  'emakigem.section.upgradeMaterials': '升级材料',
  'emakigem.section.slots': '插槽结构',
  'emakigem.section.gemLimit': '宝石限制',
  'emakigem.section.guiTemplate': 'GUI 模板',
  'emakigem.section.displayActions': '展示动作',
  'emakigem.section.matchRules': '匹配规则',
  'emakigem.section.genericBasic': '基础',
  'emakigem.cost.globalUpgrade': '全局升级经济',
  'emakigem.cost.levelOverride': '等级经济覆盖',
  'emakigem.cost.inlay': '镶嵌费用',
  'emakigem.cost.extract': '拆卸费用',
  'emakigem.cost.extractReturn': '拆卸返还',
  'emakigem.cost.currency': '货币',
  'emakigem.cost.material': '材料',
  'emakigem.action.add': '+ 添加',
  'emakigem.action.addAction': '+ 添加动作',
  'emakigem.action.addSlot': '+ 插槽',
  'emakigem.action.addCurrency': '+ 货币',
  'emakigem.action.addMaterial': '+ 材料',
  'emakigem.action.setCost': '+ 设置{label}',
  'emakigem.action.delete': '删除',
  'emakigem.action.moveUp': '上移',
  'emakigem.action.moveDown': '下移',
  'emakigem.option.effect.variables': '变量',
  'emakigem.option.effect.ea_attribute': 'Mythic 属性',
  'emakigem.option.effect.es_skill': 'Mythic 技能',
  'emakigem.option.effect.name_action': '名称动作',
  'emakigem.option.effect.lore_action': 'Lore 动作',
  'emakigem.option.extract.original': '原样返还',
  'emakigem.option.extract.destroy': '销毁',
  'emakigem.option.extract.downgrade': '降级返还',
  'emakigem.option.failure.none': '无惩罚',
  'emakigem.option.failure.downgrade': '降级',
  'emakigem.option.failure.destroy': '销毁',
  'emakigem.option.gemType.attack': '攻击',
  'emakigem.option.gemType.defense': '防御',
  'emakigem.option.gemType.utility': '功能',
  'emakigem.option.gemType.universal': '通用',
  'emakigem.item.field.id': 'ID',
  'emakigem.item.field.display_name': '显示名称',
  'emakigem.item.field.lore': 'Lore',
  'emakigem.item.field.gem_type': '宝石类型',
  'emakigem.item.field.level': '基础等级',
  'emakigem.item.field.item_sources': '物品来源',
  'emakigem.item.field.custom_model_data': '模型数据',
  'emakigem.item.field.socket_compatibility': '兼容插槽',
  'emakigem.item.field.type': '类型',
  'emakigem.item.field.variables': '变量',
  'emakigem.item.field.ea_attributes': 'Mythic 属性',
  'emakigem.item.field.es_skills': 'Mythic 技能',
  'emakigem.item.field.name_actions': '名称动作',
  'emakigem.item.field.lore_actions': 'Lore 动作',
  'emakigem.item.field.enabled': '启用',
  'emakigem.item.field.max_level': '最大等级',
  'emakigem.item.field.gui_template': 'GUI 模板',
  'emakigem.item.field.failure_penalty': '失败惩罚',
  'emakigem.item.field.success_rates': '成功率表',
  'emakigem.item.field.success_rate': '成功率',
  'emakigem.item.field.provider': '提供器',
  'emakigem.item.field.currency_id': '货币 ID',
  'emakigem.item.field.amount': '数量',
  'emakigem.item.field.base_cost': '基础费用',
  'emakigem.item.field.cost_formula': '费用公式',
  'emakigem.item.field.mode': '模式',
  'emakigem.item.field.downgrade_levels': '降级等级',
  'emakigem.item.field.degraded_chance': '损坏概率',
  'emakigem.item.field.actions.success': '成功动作',
  'emakigem.item.field.actions.failure': '失败动作',
  'emakigem.item.field.inlay_success': '镶嵌成功动作',
  'emakigem.item.field.extract_success': '拆卸成功动作',
  'emakigem.item.field.index': '索引',
  'emakigem.item.field.match.item_sources': '匹配物品来源',
  'emakigem.item.field.match.slot_groups': '匹配插槽组',
  'emakigem.item.field.match.lore_contains': 'Lore 包含',
  'emakigem.item.field.default_open_slots': '默认开启插槽',
  'emakigem.item.field.allowed_gem_types': '允许宝石类型',
  'emakigem.item.field.max_same_type': '同类型上限',
  'emakigem.item.field.max_same_id': '同 ID 上限',
  'emakigem.item.field.gui.gem_template': '宝石 GUI 模板',
  'emakigem.item.field.gui.open_template': '开孔 GUI 模板',
  'emakigem.item.field.material': '材质',
  'emakigem.actionParam.value': '文本',
  'emakigem.actionParam.regex_pattern': '正则表达式',
  'emakigem.actionParam.replacement': '替换为',
  'emakigem.actionParam.content': '内容（每行一个）',
  'emakigem.actionParam.target_pattern': '目标匹配',
  'emakigem.actionParam.anchor': '锚点'
});

const host = window.EmakiWebConsole;
if (host) {
  host.registerSurface({ kind: 'ITEM', moduleId: 'EmakiGem', editorId: 'emakigem:gem', component: EmakiGemItemSurface, label: '宝石定义', priority: 100 });
  host.registerSurface({ kind: 'ITEM', moduleId: 'EmakiGem', editorId: 'emakigem:socket-item', component: EmakiGemItemSurface, label: '宝石插槽物品', priority: 100 });
  host.registerSurface({ kind: 'GUI', moduleId: 'EmakiGem', editorId: 'emakigem:gui', component: PluginGuiSurface, label: '宝石 GUI', priority: 100 });
} else {
  console.warn('[EmakiGem] EmakiWebConsole host is not available; item surface was not registered.');
}
