import { registerModuleLocale, registerPluginGuiEditor } from 'emaki-web-console';

registerModuleLocale('EmakiGem', 'zh-CN', {
  'emakigem.surface.gem': '宝石',
  'emakigem.surface.socketItem': '插槽物品',
  'emakigem.surface.gui': '宝石 GUI',
  'emakigem.preview.aria': '宝石物品预览',
  'emakigem.preview.kind.gem': '宝石',
  'emakigem.preview.kind.socket': '插槽物品',
  'emakigem.preview.kind.generic': '物品',
  'emakigem.preview.levelTitle': '升级等级预览',
  'emakigem.preview.levelHint': '切换等级会用当前草稿重新生成 Lore 与效果。',
  'emakigem.preview.levelCurrent': '当前 Lv.{level}',
  'emakigem.preview.levelBase': '基础等级',
  'emakigem.preview.status.syncing': '同步中',
  'emakigem.preview.status.live': '实时',
  'emakigem.preview.status.failed': '预览失败',
  'emakigem.preview.empty': '暂无预览',
  'emakigem.section.basic': '基础字段',
  'emakigem.section.effects': 'effects 效果',
  'emakigem.section.legacy': '兼容旧字段',
  'emakigem.section.costReturn': '费用与返还',
  'emakigem.section.upgrade': 'upgrade 升级配置',
  'emakigem.section.gemActions': '宝石动作',
  'emakigem.section.levels': '升级等级',
  'emakigem.section.levelEffects': '等级效果',
  'emakigem.section.upgradeMaterials': '升级材料',
  'emakigem.section.slots': '插槽结构',
  'emakigem.section.gemLimit': '宝石限制',
  'emakigem.section.guiTemplate': 'GUI 模板',
  'emakigem.section.displayActions': '展示动作',
  'emakigem.section.matchRules': '匹配规则',
  'emakigem.section.genericBasic': '基础',
  'emakigem.cost.globalUpgrade': '全局升级经济',
  'emakigem.cost.levelOverride': '等级经济覆盖',
  'emakigem.cost.inlay': '镶嵌费用',
  'emakigem.cost.extract': '拆卸费用',
  'emakigem.cost.extractReturn': '拆卸返还',
  'emakigem.cost.currency': '货币',
  'emakigem.cost.material': '材料',
  'emakigem.action.add': '+ 添加',
  'emakigem.action.addAction': '+ 添加动作',
  'emakigem.action.addSlot': '+ 插槽',
  'emakigem.action.addCurrency': '+ 货币',
  'emakigem.action.addMaterial': '+ 材料',
  'emakigem.action.setCost': '+ 设置{label}',
  'emakigem.action.delete': '删除',
  'emakigem.action.moveUp': '上移',
  'emakigem.action.moveDown': '下移',
  'emakigem.option.effect.variables': '变量',
  'emakigem.option.effect.ea_attribute': 'EA 属性',
  'emakigem.option.effect.es_skill': 'ES 技能',
  'emakigem.option.effect.name_action': '名称动作',
  'emakigem.option.effect.lore_action': 'Lore 动作',
  'emakigem.option.extract.original': '原样返还',
  'emakigem.option.extract.destroy': '销毁',
  'emakigem.option.extract.downgrade': '降级返还',
  'emakigem.option.failure.none': '无惩罚',
  'emakigem.option.failure.downgrade': '降级',
  'emakigem.option.failure.destroy': '销毁',
  'emakigem.option.gemType.attack': '攻击',
  'emakigem.option.gemType.defense': '防御',
  'emakigem.option.gemType.utility': '功能',
  'emakigem.option.gemType.universal': '通用',
  'emakigem.option.economyProvider.auto': '自动选择',
  'emakigem.option.economyProvider.vault': 'Vault',
  'emakigem.option.economyProvider.excellenteconomy': 'ExcellentEconomy',
  'emakigem.field.id': 'ID',
  'emakigem.field.display_name': '显示名称',
  'emakigem.field.lore': 'Lore',
  'emakigem.field.gem_type': '宝石类型',
  'emakigem.field.level': '基础等级',
  'emakigem.field.item_sources': '物品来源',
  'emakigem.field.custom_model_data': '模型数据',
  'emakigem.field.socket_compatibility': '兼容插槽',
  'emakigem.field.type': '类型',
  'emakigem.field.variables': '变量',
  'emakigem.field.ea_attributes': 'EA 属性',
  'emakigem.field.es_skills': 'ES 技能',
  'emakigem.field.name_actions': '名称动作',
  'emakigem.field.lore_actions': 'Lore 动作',
  'emakigem.field.value': '文本',
  'emakigem.field.regex_pattern': '正则表达式',
  'emakigem.field.replacement': '替换为',
  'emakigem.field.content': '内容',
  'emakigem.field.target_pattern': '目标匹配',
  'emakigem.field.anchor': '锚点',
  'emakigem.field.inlay_cost': '镶嵌费用',
  'emakigem.field.extract_cost': '拆卸费用',
  'emakigem.field.extract_return': '拆卸返还',
  'emakigem.field.economy': '经济消耗',
  'emakigem.field.currencies': '货币消耗',
  'emakigem.field.materials': '材料消耗',
  'emakigem.field.provider': '经济提供器',
  'emakigem.field.currency_id': '货币 ID',
  'emakigem.field.amount': '数量',
  'emakigem.field.base_cost': '基础费用',
  'emakigem.field.cost_formula': '费用公式',
  'emakigem.field.enabled': '启用',
  'emakigem.field.mode': '返还模式',
  'emakigem.field.downgrade_levels': '降级等级',
  'emakigem.field.degraded_chance': '降级概率',
  'emakigem.field.upgrade': '升级配置',
  'emakigem.field.max_level': '最高等级',
  'emakigem.field.gui_template': '升级 GUI 模板',
  'emakigem.field.failure_penalty': '失败惩罚',
  'emakigem.field.success_rates': '成功率表',
  'emakigem.field.levels': '等级配置',
  'emakigem.field.success_rate': '成功率',
  'emakigem.field.success_chance': '成功概率',
  'emakigem.field.actions': '动作',
  'emakigem.field.actions.success': '成功动作',
  'emakigem.field.actions.failure': '失败动作',
  'emakigem.field.inlay_success': '镶嵌成功动作',
  'emakigem.field.extract_success': '拆卸成功动作',
  'emakigem.field.index': '索引',
  'emakigem.field.match.item_sources': '匹配物品来源',
  'emakigem.field.match.slot_groups': '装备分组',
  'emakigem.field.match.lore_contains': 'Lore 包含',
  'emakigem.field.default_open_slots': '默认开放插槽',
  'emakigem.field.allowed_gem_types': '允许宝石类型',
  'emakigem.field.max_same_type': '同类型上限',
  'emakigem.field.max_same_id': '同 ID 上限',
  'emakigem.field.gui.gem_template': '宝石 GUI 模板',
  'emakigem.field.gui.open_template': '开孔 GUI 模板',
  'emakigem.field.material': '材质',
  'emakigem.item.field.id': 'ID',
  'emakigem.item.field.display_name': '显示名称',
  'emakigem.item.field.lore': 'Lore',
  'emakigem.item.field.gem_type': '宝石类型',
  'emakigem.item.field.level': '基础等级',
  'emakigem.item.field.item_sources': '物品来源',
  'emakigem.item.field.custom_model_data': '模型数据',
  'emakigem.item.field.socket_compatibility': '兼容插槽',
  'emakigem.item.field.type': '类型',
  'emakigem.item.field.variables': '变量',
  'emakigem.item.field.ea_attributes': 'EA 属性',
  'emakigem.item.field.es_skills': 'ES 技能',
  'emakigem.item.field.name_actions': '名称动作',
  'emakigem.item.field.lore_actions': 'Lore 动作',
  'emakigem.item.field.enabled': '启用',
  'emakigem.item.field.max_level': '最大等级',
  'emakigem.item.field.gui_template': 'GUI 模板',
  'emakigem.item.field.failure_penalty': '失败惩罚',
  'emakigem.item.field.success_rates': '成功率表',
  'emakigem.item.field.success_rate': '成功率',
  'emakigem.item.field.success_chance': '成功概率',
  'emakigem.item.field.provider': '经济提供器',
  'emakigem.item.field.currency_id': '货币 ID',
  'emakigem.item.field.amount': '数量',
  'emakigem.item.field.base_cost': '基础费用',
  'emakigem.item.field.cost_formula': '费用公式',
  'emakigem.item.field.mode': '模式',
  'emakigem.item.field.downgrade_levels': '降级等级',
  'emakigem.item.field.degraded_chance': '降级概率',
  'emakigem.item.field.actions.success': '成功动作',
  'emakigem.item.field.actions.failure': '失败动作',
  'emakigem.item.field.inlay_success': '镶嵌成功动作',
  'emakigem.item.field.extract_success': '拆卸成功动作',
  'emakigem.item.field.index': '索引',
  'emakigem.item.field.match.item_sources': '匹配物品来源',
  'emakigem.item.field.match.slot_groups': '匹配插槽组',
  'emakigem.item.field.match.lore_contains': 'Lore 包含',
  'emakigem.item.field.default_open_slots': '默认开启插槽',
  'emakigem.item.field.allowed_gem_types': '允许宝石类型',
  'emakigem.item.field.max_same_type': '同类型上限',
  'emakigem.item.field.max_same_id': '同 ID 上限',
  'emakigem.item.field.gui.gem_template': '宝石 GUI 模板',
  'emakigem.item.field.gui.open_template': '开孔 GUI 模板',
  'emakigem.item.field.material': '材质',
  'emakigem.actionParam.value': '文本',
  'emakigem.actionParam.regex_pattern': '正则表达式',
  'emakigem.actionParam.replacement': '替换为',
  'emakigem.actionParam.content': '内容（每行一个）',
  'emakigem.actionParam.target_pattern': '目标匹配',
  'emakigem.actionParam.anchor': '锚点'
});

registerPluginGuiEditor({
  moduleId: 'EmakiGem',
  editorId: 'emakigem:gui',
  label: '宝石 GUI',
  fields: [
    ['slots', '槽位', 'GUI 中所有可渲染槽位配置。', 'object'],
    ['type', '槽位类型', '插件业务识别的槽位语义，例如 target_item、confirm。', 'text'],
    ['hidden_components', '隐藏组件', '隐藏 tooltip、附魔、属性等原版组件。', 'stringList'],
    ['item_model', '物品模型', '资源包 item model 标识。', 'text'],
    ['custom_model_data', '模型数据', 'Custom Model Data 数值。', 'number'],
    ['sounds', '声音', '点击槽位时播放的声音配置。', 'object'],
    ['target_item', '目标装备槽', '放入待镶嵌或查看的装备。', 'text'],
    ['socket_slot', '宝石槽位', '展示或操作装备上的宝石槽。', 'text'],
    ['confirm', '确认按钮', '确认当前宝石操作。', 'text']
  ]
});

