package emaki.jiuwu.craft.corelib.script.js.registration;

public enum JavaScriptRegistrationType {
    ACTION,
    PLACEHOLDER,
    EVENT,
    EXPRESSION_FUNCTION,
    CONDITION,
    ITEM_DEFINITION,
    ITEM_FACTORY,
    LEVEL_EXP_RULE,
    LEVEL_UP_HOOK,
    STRENGTHEN_CHANCE_RULE,
    STRENGTHEN_RESULT_HOOK,
    COOKING_RESULT_RULE,
    COOKING_COMPLETE_HOOK,
    FORGE_RULE,
    FORGE_RESULT_HOOK,
    GEM_SOCKET_RULE,
    GEM_SET_BONUS
}
