package emaki.jiuwu.craft.item.model;

public enum RefreshFullReason {
    JOIN,
    PICKUP,
    COLLECT_TO_CURSOR,
    DOUBLE_CLICK,
    UNKNOWN_ACTION,
    UNKNOWN_CLICK,
    HOTBAR_MOVE_AND_READD,
    TOP_TO_PLAYER_SHIFT,
    SLOT_CONVERSION_FAILED,
    ACTION_CLICK_MISMATCH,
    UNSUPPORTED_CONTEXT,
    EXPLICIT_FULL,
    CACHE_MISS,
    CACHE_INVALID,
    ITEM_GENERATION_CHANGED,
    SET_GENERATION_CHANGED,
    DIRTY_SCOPE_INCOMPLETE,
    CONTRIBUTION_SIGNATURE_CHANGED,
    COMPARE_CONFLICT
}
