package emaki.jiuwu.craft.corelib.action;

public enum ActionErrorType {
    NONE,
    INVALID_ARGUMENT,
    OPERATION_NOT_FOUND,
    EXECUTION_EXCEPTION,
    INVALID_STATE,
    PROVIDER_UNAVAILABLE,
    CURRENCY_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    WORLD_NOT_FOUND,
    TEMPLATE_NOT_FOUND,
    SYNTAX_ERROR,
    UNSUPPORTED
}
