name: EmakiSkills
main: emaki.jiuwu.craft.skills.EmakiSkillsPlugin
version: ${project.version}
api-version: "1.21"
folia-supported: true
depend:
  - EmakiCoreLib
softdepend:
  - MythicMobs
  - EmakiAttribute
  - PlaceholderAPI
  - AuraSkills
  - MythicLib
  - MMOCore
commands:
  emakiskills:
    aliases: [eskills]
    permission: emakiskills.use
permissions:
  emakiskills.use:
    default: true
  emakiskills.reload:
    default: op
  emakiskills.admin:
    default: op
  emakiskills.debug:
    default: op
