// EmakiSkills（原 EmakiSkills/pom.xml，private-modules profile 模块）。
version = '2.8.7'

dependencies {
    // 原 shade artifactSet 白名单。
    shadeBundle project(':EmakiSkillsApi')

    // 原 compile 作用域。
    api project(':EmakiCoreLibApi')
    api project(':EmakiCoreLib')
    api project(':EmakiSkillsApi')

    // 原 provided 作用域。
    provided project(':EmakiAttributeApi')
    provided libs.paper.api
    provided libs.graalvm.polyglot
    provided libs.mythic.dist
    provided libs.placeholderapi
    provided libs.jetbrains.annotations

    // 原 test 作用域。
    testImplementation libs.junit.jupiter
    testImplementation project(':EmakiAttribute')
    testImplementation libs.boosted.yaml
    testImplementation libs.mockbukkit
}
