id: "open/default"
title: "<dark_gray>开孔台</dark_gray>"
rows: 4
slots:
  top_frame:
    slots: [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
    item: "GRAY_STAINED_GLASS_PANE"
    display_name: "<gray>"
    hidden_components: [ "tooltip" ]

  bottom_frame:
    slots: [ 27, 28, 29, 31, 32, 33, 34, 35 ]
    item: "GRAY_STAINED_GLASS_PANE"
    display_name: "<gray>"
    hidden_components: [ "tooltip" ]

  side_frame:
    slots: [ 9, 17, 18, 26 ]
    item: "BLACK_STAINED_GLASS_PANE"
    display_name: "<dark_gray>"
    hidden_components: [ "tooltip" ]

  target_item:
    slots: [ 10 ]
    type: "target_item"
    item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    display_name: "<aqua>放入装备</aqua>"

  opener_item:
    slots: [ 16 ]
    type: "opener_item"
    item: "AMETHYST_SHARD"
    display_name: "<light_purple>放入开孔器</light_purple>"

  socket_info:
    slots: [ 19 ]
    type: "socket_info"
    item: "BOOK"
    display_name: "<gold>开孔信息</gold>"

  socket_slots:
    slots: [ 12, 13, 14, 21, 22, 23 ]
    type: "socket_slot"
    item: "WHITE_STAINED_GLASS_PANE"
    display_name: "<white>锁定插槽</white>"

  preview_display:
    slots: [ 25 ]
    type: "preview_display"
    item: "WRITABLE_BOOK"
    display_name: "<gold>开孔预览</gold>"

  confirm:
    slots: [ 30 ]
    type: "confirm"
    item: "LIME_STAINED_GLASS_PANE"
    display_name: "<green>确认开孔</green>"
