import { getLocale, registerModuleLocale, registerPluginConfig, registerPluginGuiEditor } from 'emaki-web-console';

const MODULE = 'EmakiCooking';

type FieldSpec = [path: string, label: string, comment: string, type: string, extra?: Record<string, unknown>];

const copy = (zh: string, en: string) => getLocale().startsWith('zh') ? zh : en;

const displayTransformFields = [
  { path: 'offset', label: '偏移', comment: '展示实体相对工位方块的 x/y/z 偏移。', type: 'object', defaultValue: {} },
  { path: 'offset.x', label: 'X 偏移', comment: 'X 轴偏移。', type: 'number', defaultValue: 0 },
  { path: 'offset.y', label: 'Y 偏移', comment: 'Y 轴偏移。', type: 'number', defaultValue: 0 },
  { path: 'offset.z', label: 'Z 偏移', comment: 'Z 轴偏移。', type: 'number', defaultValue: 0 },
  { path: 'rotation', label: '旋转', comment: '展示实体的 x/y/z 旋转角度或范围。', type: 'object', defaultValue: {} },
  { path: 'rotation.x', label: 'X 旋转', comment: 'X 轴旋转。', type: 'text', defaultValue: '0' },
  { path: 'rotation.y', label: 'Y 旋转', comment: 'Y 轴旋转。', type: 'text', defaultValue: '0' },
  { path: 'rotation.z', label: 'Z 旋转', comment: 'Z 轴旋转。', type: 'text', defaultValue: '0' },
  { path: 'scale', label: '缩放', comment: '展示实体的 x/y/z 缩放倍率。', type: 'object', defaultValue: {} },
  { path: 'scale.x', label: 'X 缩放', comment: 'X 轴缩放。', type: 'number', defaultValue: 1 },
  { path: 'scale.y', label: 'Y 缩放', comment: 'Y 轴缩放。', type: 'number', defaultValue: 1 },
  { path: 'scale.z', label: 'Z 缩放', comment: 'Z 轴缩放。', type: 'number', defaultValue: 1 }
];

const itemAdjustmentFields: FieldSpec[] = [
  ['item_sources', '物品来源', '需要调整展示姿态的 ItemSource 列表。', 'stringList'],
  ['adjustment', '展示调整', '此物品自己的展示实体偏移、旋转和缩放。', 'object'],
  ['adjustment.offset', '偏移', '展示实体偏移。', 'object'],
  ['adjustment.offset.x', 'X 偏移', 'X 轴偏移。', 'number'],
  ['adjustment.offset.y', 'Y 偏移', 'Y 轴偏移。', 'number'],
  ['adjustment.offset.z', 'Z 偏移', 'Z 轴偏移。', 'number'],
  ['adjustment.rotation', '旋转', '展示实体旋转。', 'object'],
  ['adjustment.rotation.x', 'X 旋转', 'X 轴旋转角度或范围。', 'text'],
  ['adjustment.rotation.y', 'Y 旋转', 'Y 轴旋转角度或范围。', 'text'],
  ['adjustment.rotation.z', 'Z 旋转', 'Z 轴旋转角度或范围。', 'text'],
  ['adjustment.scale', '缩放', '展示实体缩放。', 'object'],
  ['adjustment.scale.x', 'X 缩放', 'X 轴缩放。', 'number'],
  ['adjustment.scale.y', 'Y 缩放', 'Y 轴缩放。', 'number'],
  ['adjustment.scale.z', 'Z 缩放', 'Z 轴缩放。', 'number'],
  ['stations', '工位覆盖', '按工位类型覆盖展示调整。', 'object']
];

const inputItemFields = [
  { path: 'item_sources', label: '物品来源', comment: '可匹配该输入的 ItemSource 列表。', type: 'stringList', defaultValue: ['minecraft-carrot'] },
  { path: 'amount', label: '数量', comment: '需要投入的数量。', type: 'number', defaultValue: 1 }
];

const outputFields = [
  { path: 'item_sources', label: '产物来源', comment: '产物 ItemSource 列表。', type: 'stringList', defaultValue: ['minecraft-bread'] },
  { path: 'amount', label: '数量', comment: '生成的产物数量。', type: 'number', defaultValue: 1 },
  { path: 'chance', label: '概率', comment: '产出概率；留空时按必定产出处理。', type: 'number', defaultValue: 100 },
  { path: 'actions', label: '产物动作', comment: '此产物生成后执行的动作。', type: 'stringList', defaultValue: [] },
  { path: 'structured_presentation', label: '结构化展示', comment: '覆盖产物展示层的结构化呈现配置。', type: 'map', defaultValue: {} }
];

const outcomeFields = [
  { path: 'item_sources', label: '产物来源', comment: '单产物 ItemSource 列表；源码会把该对象作为直接产物。', type: 'stringList', defaultValue: ['minecraft-bread'] },
  { path: 'amount', label: '数量', comment: '生成的产物数量。', type: 'number', defaultValue: 1 },
  { path: 'actions', label: '产物动作', comment: '该结果触发后执行的动作。', type: 'stringList', defaultValue: [] },
  { path: 'outputs', label: '多产物', comment: '该结果可产出的多个物品；存在时源码优先按 outputs 列表发放。', type: 'objectList', defaultValue: [], itemFields: outputFields },
  { path: 'structured_presentation', label: '结构化展示', comment: '覆盖结果展示层的结构化呈现配置。', type: 'map', defaultValue: {} }
];

const fields: FieldSpec[] = [
  ['language', '语言', '语言文件 ID，对应 lang/<language>.yml。', 'text'],
  ['version', '配置版本', '默认配置结构版本，通常不建议手动修改。', 'text'],
  ['release_default_data', '释放默认数据', '首次启动或缺失 recipes/、item_adjustments/ 等示例数据时是否释放默认文件。', 'boolean'],
  ['input_rules', '输入限制', '控制工位输入物品是否必须继续匹配当前配方，避免玩家把无关物品塞入工位。', 'object'],
  ['input_rules.only_recipe_items', '严格模式', '开启后只允许当前工位配方可继续匹配的原料进入输入槽；关闭后允许更宽松的放入逻辑。', 'boolean'],
  ['display_entities', '展示实体', '工位上方食材展示实体的全局渲染策略、可视距离和刷新节奏。', 'object'],
  ['display_entities.backend', '渲染后端', '展示实体使用的后端。auto 会优先尝试 PacketEvents，不可用时回退 Bukkit。', 'enum', { options: ['auto', 'packet_events', 'bukkit'], optionLabelPrefix: 'display_entities.backend' }],
  ['display_entities.view_distance_blocks', '可视距离', '玩家距离工位超过该格数后不再接收展示实体刷新。', 'number'],
  ['display_entities.refresh_interval_ticks', '刷新间隔', '展示实体位置、旋转、可见性与状态刷新间隔，单位 tick。', 'number'],
  ['display_entities.wok', '炒锅展示', '炒锅食材环形展示的专用布局参数。', 'object'],
  ['display_entities.wok.layout_radius', '炒锅半径', '炒锅中多份食材围绕中心摆放的半径，单位方块格。', 'number'],
  ['display_adjustments', '展示变换', '默认展示实体的偏移、旋转、缩放，以及各工位专用覆盖。', 'object'],
  ['display_adjustments.defaults', '默认展示', '普通物品和方块展示实体的默认变换参数。', 'object', { creatableChildren: true, createTemplates: [{ id: 'display-kind-adjustment', label: copy('展示类型调整', 'Display kind adjustment'), fields: displayTransformFields }] }],
  ['display_adjustments.station_defaults', '工位覆盖', '按工位类型覆盖展示实体变换，例如炒锅食材翻转角度。', 'object', { creatableChildren: true, createTemplates: [{ id: 'station-display-adjustment', label: copy('工位展示调整', 'Station display adjustment'), fields: [{ path: 'item', label: '物品展示', comment: '该工位物品展示实体的调整。', type: 'object', defaultValue: {}, itemFields: displayTransformFields }] }] }],
  ['stations', '工位设置', '砧板、炒锅、研磨机、蒸锅、烤炉、榨汁机和发酵桶的运行规则。', 'object'],
  ['stations.chopping_board', '砧板', '砧板方块匹配、交互、厨刀识别、切割伤害与动作反馈。', 'object'],
  ['stations.chopping_board.block_item_sources', '砧板方块来源', '识别为砧板本体方块的 ItemSource 列表。', 'list'],
  ['stations.chopping_board.only_recipe_items', '砧板严格输入', '是否只允许砧板配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.chopping_board.interactions', '砧板交互绑定', '砧板各业务动作对应的玩家点击方式。', 'object'],
  ['stations.chopping_board.drop_result', '砧板掉落产物', '砧板完成后是否直接掉落产物。', 'boolean'],
  ['stations.chopping_board.space_restriction', '空间限制', '砧板切割时是否要求上方空间满足展示与掉落需求。', 'boolean'],
  ['stations.chopping_board.interaction_delay_ms', '砧板交互间隔', '同一玩家连续触发砧板交互的最小间隔，单位毫秒。', 'number'],
  ['stations.chopping_board.tool_item_sources', '厨刀来源', '识别为厨刀的 ItemSource 列表。', 'list'],
  ['stations.chopping_board.cut_damage', '切割伤害', '砧板切割失败或误伤时的伤害开关、概率与数值。', 'object'],
  ['stations.chopping_board.cut_damage.enabled', '启用切割伤害', '是否启用砧板切割伤害。', 'boolean'],
  ['stations.chopping_board.cut_damage.chance', '切割伤害概率', '触发砧板切割伤害的概率。', 'number'],
  ['stations.chopping_board.cut_damage.value', '切割伤害值', '砧板切割伤害数值。', 'number'],
  ['stations.wok', '炒锅', '炒锅方块匹配、翻炒、火候、失败产物、动画与烫伤规则。', 'object'],
  ['stations.wok.block_item_sources', '炒锅方块来源', '识别为炒锅本体方块的 ItemSource 列表。', 'list'],
  ['stations.wok.only_recipe_items', '炒锅严格输入', '是否只允许炒锅配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.wok.interactions', '炒锅交互绑定', '炒锅各业务动作对应的玩家点击方式。', 'object'],
  ['stations.wok.drop_result', '炒锅掉落产物', '炒锅完成后是否直接掉落产物。', 'boolean'],
  ['stations.wok.need_bowl', '需要碗', '出锅时是否要求玩家提供碗类容器。', 'boolean'],
  ['stations.wok.stir_delay_ms', '翻炒间隔', '两次翻炒动作之间的最小间隔，单位毫秒。', 'number'],
  ['stations.wok.timeout_ms', '炒锅超时', '炒锅状态超过该时间未处理时按过火或失败处理。', 'number'],
  ['stations.wok.spatula_item_sources', '锅铲来源', '识别为锅铲的 ItemSource 列表。', 'list'],
  ['stations.wok.heat_levels', '火候等级', '按下方热源 ItemSource 映射到的火候等级列表。', 'list'],
  ['stations.wok.ignite_heat_source', '点亮热源', '放入燃料或食材后是否尝试点亮下方热源。', 'boolean'],
  ['stations.wok.scald_damage', '烫伤伤害', '炒锅对玩家造成烫伤的开关与伤害值。', 'object'],
  ['stations.wok.scald_damage.enabled', '启用烫伤', '是否启用炒锅烫伤。', 'boolean'],
  ['stations.wok.scald_damage.value', '烫伤数值', '炒锅烫伤伤害数值。', 'number'],
  ['stations.wok.stir_animation', '翻炒动画', '炒锅翻炒时食材抛起、旋转和持续时间。', 'object'],
  ['stations.wok.stir_animation.enabled', '启用翻炒动画', '是否启用炒锅翻炒动画。', 'boolean'],
  ['stations.wok.stir_animation.duration_ticks', '动画持续 tick', '翻炒动画持续时间。', 'number'],
  ['stations.wok.stir_animation.height', '动画高度', '翻炒动画抛起高度。', 'number'],
  ['stations.wok.stir_animation.rotation_axis', '旋转轴', '翻炒动画旋转轴。', 'enum', { options: ['x', 'y', 'z'], optionLabelPrefix: 'axis' }],
  ['stations.wok.stir_animation.rotation_degrees', '旋转角度', '翻炒动画旋转角度。', 'number'],
  ['stations.wok.failure', '炒锅失败规则', '炒锅处理失败时的概率、产物与反馈。', 'object'],
  ['stations.wok.failure.enabled', '启用失败规则', '是否启用炒锅失败规则。', 'boolean'],
  ['stations.wok.failure.chance', '失败概率', '炒锅失败触发概率。', 'number'],
  ['stations.wok.failure.item_sources', '失败产物', '炒锅失败时使用的产物来源。', 'list'],
  ['stations.wok.invalid_result_item_sources', '无效产物', '炒锅结果无效时使用的兜底产物来源。', 'list'],
  ['stations.grinder', '研磨机', '研磨机方块匹配、启动交互、检查周期和运行反馈。', 'object'],
  ['stations.grinder.block_item_sources', '研磨机方块来源', '识别为研磨机本体方块的 ItemSource 列表。', 'list'],
  ['stations.grinder.only_recipe_items', '研磨机严格输入', '是否只允许研磨机配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.grinder.interactions', '研磨机交互绑定', '研磨机各业务动作对应的玩家点击方式。', 'object'],
  ['stations.grinder.drop_result', '研磨机掉落产物', '研磨完成后是否直接掉落产物。', 'boolean'],
  ['stations.grinder.check_delay_ticks', '研磨检查周期', '研磨机后台检查间隔，单位 tick。', 'number'],
  ['stations.steamer', '蒸锅', '蒸锅 GUI、燃料、水分、蒸汽效率和热源点亮规则。', 'object'],
  ['stations.steamer.block_item_sources', '蒸锅方块来源', '识别为蒸锅本体方块的 ItemSource 列表。', 'list'],
  ['stations.steamer.only_recipe_items', '蒸锅严格输入', '是否只允许蒸锅配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.steamer.interactions', '蒸锅交互绑定', '蒸锅各业务动作对应的玩家点击方式。', 'object'],
  ['stations.steamer.drop_result', '蒸锅掉落产物', '蒸制完成后是否直接掉落产物。', 'boolean'],
  ['stations.steamer.heat_item_sources', '蒸锅热源来源', '识别为蒸锅热源的方块 ItemSource 列表。', 'list'],
  ['stations.steamer.ignite_heat_source', '蒸锅点亮热源', '放入燃料或食材后是否尝试点亮蒸锅热源。', 'boolean'],
  ['stations.steamer.fuels', '蒸锅燃料', '蒸锅可投入燃料及其燃烧时间配置。', 'list'],
  ['stations.steamer.moisture_rules', '水分规则', '蒸锅可转化为水分的输入物和返还物配置。', 'list'],
  ['stations.steamer.reset_progress_when_steam_empty', '蒸汽耗尽重置', '蒸汽耗尽时是否重置当前蒸制进度。', 'boolean'],
  ['stations.steamer.steam_production_efficiency', '产汽效率', '每周期最多把多少水分转换为蒸汽。', 'number'],
  ['stations.steamer.steam_conversion_efficiency', '蒸汽转进度', '每次蒸汽消耗换算成多少烹饪进度。', 'number'],
  ['stations.steamer.steam_consumption_efficiency', '蒸汽消耗', '每个周期基础蒸汽消耗量。', 'number'],
  ['stations.oven', '烤炉', '烤炉 GUI、燃料、火力区间与热量衰减规则。', 'object'],
  ['stations.oven.block_item_sources', '烤炉方块来源', '识别为烤炉本体方块的 ItemSource 列表。', 'list'],
  ['stations.oven.only_recipe_items', '烤炉严格输入', '是否只允许烤炉配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.oven.interactions', '烤炉交互绑定', '烤炉各业务动作对应的玩家点击方式。', 'object'],
  ['stations.oven.drop_result', '烤炉掉落产物', '烘烤完成后是否直接掉落产物。', 'boolean'],
  ['stations.oven.heat_item_sources', '烤炉热源来源', '识别为烤炉热源的方块 ItemSource 列表。', 'list'],
  ['stations.oven.ignite_heat_source', '烤炉点亮热源', '放入燃料或食材后是否尝试点亮烤炉热源。', 'boolean'],
  ['stations.oven.fuels', '烤炉燃料', '烤炉可投入燃料及其持续时间、火力配置。', 'list'],
  ['stations.oven.heat', '烤炉火力', '烤炉火力区间与自然衰减。', 'object'],
  ['stations.oven.heat.min', '最低火力', '允许推进烘烤流程的最低火力。', 'number'],
  ['stations.oven.heat.max', '最高火力', '允许推进烘烤流程的最高火力。', 'number'],
  ['stations.oven.heat.decay_per_second', '火力衰减', '烤炉火力每秒自然衰减值。', 'number'],
  ['stations.juicer', '榨汁机', '榨汁机 GUI、容器、流体容量、盛取量与完成产物处理。', 'object'],
  ['stations.juicer.block_item_sources', '榨汁机方块来源', '识别为榨汁机本体方块的 ItemSource 列表。', 'list'],
  ['stations.juicer.only_recipe_items', '榨汁机严格输入', '是否只允许榨汁机配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.juicer.interactions', '榨汁机交互绑定', '榨汁机各业务动作对应的玩家点击方式。', 'object'],
  ['stations.juicer.drop_result', '榨汁机掉落产物', '榨汁完成后是否直接掉落产物。', 'boolean'],
  ['stations.juicer.require_container', '需要容器', '榨汁或盛取时是否要求玩家提供容器。', 'boolean'],
  ['stations.juicer.max_fluid_ml', '最大容量 ml', '榨汁机内部流体容量上限。', 'number'],
  ['stations.juicer.default_serving_ml', '默认盛取 ml', '每次盛取默认消耗的流体量。', 'number'],
  ['stations.juicer.container_item_sources', '容器来源', '允许作为容器的 ItemSource 列表。', 'list'],
  ['stations.fermentation_barrel', '发酵桶', '发酵桶 GUI、密封、暂停、发酵启动与收取规则。', 'object'],
  ['stations.fermentation_barrel.block_item_sources', '发酵桶方块来源', '识别为发酵桶本体方块的 ItemSource 列表。', 'list'],
  ['stations.fermentation_barrel.only_recipe_items', '发酵桶严格输入', '是否只允许发酵桶配方可继续匹配的物品进入输入。', 'boolean'],
  ['stations.fermentation_barrel.interactions', '发酵桶交互绑定', '发酵桶各业务动作对应的玩家点击方式。', 'object'],
  ['stations.fermentation_barrel.drop_result', '发酵桶掉落产物', '发酵完成后是否直接掉落产物。', 'boolean'],
  ['stations.fermentation_barrel.drop_completed_result_on_break', '破坏掉落成品', '工位被破坏时是否掉落已经完成但未取出的产物。', 'boolean'],
  ['stations.fermentation_barrel.pause_when_open', '打开时暂停', 'GUI 打开时是否暂停发酵或后台处理进度。', 'boolean'],
  ['stations.fermentation_barrel.require_sealed', '需要密封', '发酵桶开始或推进时是否要求处于密封状态。', 'boolean']
];

const recipeFields: FieldSpec[] = [
  ['id', 'ID', '烹饪配方唯一标识。', 'text'],
  ['display_name', '显示名称', '配方在 GUI、日志或提示中的显示名称。', 'text'],
  ['input', '单输入', '单个输入物品配置，常用于烤炉、榨汁机等工位。', 'object'],
  ['input.item_sources', '输入来源', '可匹配该输入的 ItemSource 列表。', 'stringList'],
  ['inputs', '多输入', '多个输入物品配置，常用于研磨、蒸制或发酵链路。', 'objectList'],
  ['ingredients', '食材列表', '炒锅配方需要的食材记录列表，包含来源、数量和翻炒规则。', 'objectList'],
  ['cuts_required', '切割次数', '砧板配方完成所需切割次数。', 'number'],
  ['tool_damage', '工具损耗', '砧板切割时工具损耗值。', 'number'],
  ['damage_override', '伤害覆盖', '砧板切割伤害覆盖。', 'object'],
  ['damage_override.chance', '伤害概率', '切割伤害触发概率。', 'number'],
  ['damage_override.value', '伤害值', '切割伤害数值。', 'number'],
  ['grind_time_seconds', '研磨秒数', '研磨机完成所需时间。', 'number'],
  ['required_steam', '所需蒸汽', '蒸锅完成所需蒸汽总量。', 'number'],
  ['bake_time_seconds', '烘烤秒数', '烤炉基础烘烤时间。', 'number'],
  ['baking', '烘烤控制', '烤炉完美火力、完美比例和过烤时间。', 'object'],
  ['baking.perfect_heat.min', '完美火力下限', '烤炉完美火力范围下限。', 'number'],
  ['baking.perfect_heat.max', '完美火力上限', '烤炉完美火力范围上限。', 'number'],
  ['baking.perfect_required_ratio', '完美比例', '需要处于完美火力范围内的时间占比。', 'number'],
  ['baking.overbake_seconds', '过烤秒数', '超过完成时间多少秒后视为过烤。', 'number'],
  ['presses_required', '按压次数', '榨汁机完成所需按压次数。', 'number'],
  ['fluid', '流体', '榨汁机产出流体配置。', 'object'],
  ['fluid.id', '流体 ID', '流体类型标识。', 'text'],
  ['fluid.display_name', '流体显示名', '流体展示名称。', 'text'],
  ['fluid.amount_ml', '流体毫升', '每次配方产生的流体量。', 'number'],
  ['container', '容器', '榨汁机收集容器配置。', 'object'],
  ['container.item_sources', '容器来源', '可用于收集流体的容器 ItemSource。', 'stringList'],
  ['container.serving_ml', '容器容量', '每个容器可装的流体量。', 'number'],
  ['fermentation_time_seconds', '发酵秒数', '发酵桶完成所需时间。', 'number'],
  ['fermentation', '发酵控制', '发酵早收和过时规则。', 'object'],
  ['fermentation.early_collect.min_progress_ratio', '早收最小进度', '允许提前收取的最小进度比例。', 'number'],
  ['fermentation.over_time_seconds', '过发酵秒数', '完成后超过多久进入过时处理。', 'number'],
  ['heat_level', '火候等级', '炒锅或热源配方要求的火候等级。', 'number'],
  ['fault_tolerance', '容错次数', '炒锅翻炒或步骤容错次数。', 'number'],
  ['stir_total.min', '最少翻炒', '炒锅要求的最少翻炒次数。', 'number'],
  ['stir_total.max', '最多翻炒', '炒锅允许的最多翻炒次数。', 'number'],
  ['requires_previous_step', '前置步骤', '链式配方要求的前置步骤 ID。', 'text'],
  ['permission', '权限', '使用此配方所需权限节点；留空表示不限制。', 'text'],
  ['condition_type', '条件逻辑', '配方条件表达式组合方式。', 'enum', { options: ['all_of', 'any_of'], optionLabelPrefix: 'condition_type' }],
  ['conditions', '条件列表', 'CoreLib 条件表达式列表，源码按 condition_type 组合判定。', 'objectList'],
  ['condition_required_count', '需要满足数量', 'any_of 条件逻辑下需要满足的最少条件数量；0 表示不额外限制。', 'number'],
  ['structured_presentation', '结构化展示', '配方层展示配置，会与产物层展示合并。', 'object'],
  ['result', '结果', '配方完成后的产物与动作。', 'object'],
  ['result.output', '单产物', '单个产物配置。', 'object', { itemFields: outcomeFields }],
  ['result.output.item_sources', '产物来源', '单产物 ItemSource 列表。', 'stringList'],
  ['result.output.amount', '产物数量', '单产物数量。', 'number'],
  ['result.output.actions', '产物动作', '产物生成后执行的动作。', 'stringList'],
  ['result.output.outputs', '单结果多产物', '单个结果对象中的多产物列表。', 'objectList', { itemFields: outputFields }],
  ['result.outputs', '多产物', '多个产物配置列表。', 'objectList'],
  ['result.actions', '结果动作', '配方完成后执行的动作列表。', 'stringList'],
  ['result.success', '炒锅成功产物', '炒锅正确烹饪时的结果对象。', 'object', { itemFields: outcomeFields }],
  ['result.success.item_sources', '成功产物来源', '炒锅成功产物 ItemSource 列表。', 'stringList'],
  ['result.success.amount', '成功产物数量', '炒锅成功产物数量。', 'number'],
  ['result.success.actions', '成功动作', '成功产物触发动作。', 'stringList'],
  ['result.undercooked', '未熟产物', '炒锅翻炒不足时的结果对象。', 'object', { itemFields: outcomeFields }],
  ['result.undercooked.item_sources', '未熟产物来源', '未熟产物 ItemSource 列表。', 'stringList'],
  ['result.undercooked.amount', '未熟产物数量', '未熟产物数量。', 'number'],
  ['result.overcooked', '过熟产物', '炒锅翻炒过度时的结果对象。', 'object', { itemFields: outcomeFields }],
  ['result.overcooked.item_sources', '过熟产物来源', '过熟产物 ItemSource 列表。', 'stringList'],
  ['result.overcooked.amount', '过熟产物数量', '过熟产物数量。', 'number'],
  ['result.invalid', '无效产物', '炒锅食材组合错误时的结果对象。', 'object', { itemFields: outcomeFields }],
  ['result.invalid.item_sources', '无效产物来源', '无效产物 ItemSource 列表。', 'stringList'],
  ['result.invalid.amount', '无效产物数量', '无效产物数量。', 'number'],
  ['result.perfect_output', '完美烘烤产物', '烤炉完美火力完成时的覆盖产物。', 'object', { itemFields: outcomeFields }],
  ['result.overbaked_output', '过烤产物', '烤炉过烤完成时的覆盖产物。', 'object', { itemFields: outcomeFields }],
  ['fermentation.early_collect.output', '早收产物', '发酵提前收取时的产物。', 'object', { itemFields: outcomeFields }],
  ['fermentation.over_output', '过发酵产物', '发酵超时后的产物。', 'object', { itemFields: outcomeFields }]
];

const fieldComments: Record<string, [string, string, string]> = {
  block_item_sources: ['方块来源', '识别为该工位本体方块的 ItemSource 列表，可使用 minecraft-/CraftEngine/ItemsAdder/Nexo 等格式。', 'list'],
  only_recipe_items: ['只允许配方物', '是否只允许能继续匹配工位配方的物品进入输入。省略时通常继承全局输入规则。', 'boolean'],
  interactions: ['交互绑定', '不同业务动作对应的玩家点击方式，例如 shift_left_click、right_click。', 'object'],
  place_input: ['放入输入', '玩家把输入物品放入工位时使用的交互方式。', 'enum'],
  process: ['处理交互', '玩家触发加工、按压或切割时使用的交互方式。', 'enum'],
  return_input: ['返还输入', '玩家取回输入物品时使用的交互方式。', 'enum'],
  add_ingredient: ['加入食材', '玩家向炒锅加入食材时使用的交互方式或动作阶段。', 'enum'],
  stir: ['翻炒', '玩家翻炒炒锅时使用的交互方式或动作阶段。', 'enum'],
  serve: ['盛取', '玩家盛取成品时使用的交互方式或动作阶段。', 'enum'],
  return_ingredient: ['返还食材', '玩家从炒锅取回食材时使用的交互方式。', 'enum'],
  inspect: ['查看', '玩家查看工位状态时使用的交互方式。', 'enum'],
  start: ['启动', '玩家启动工位时使用的交互方式或动作阶段。', 'enum'],
  open: ['打开', '玩家打开工位 GUI 时使用的交互方式。', 'enum'],
  fuel: ['燃料', '玩家投入燃料时使用的交互方式或动作阶段。', 'enum'],
  complete: ['完成', '工位完成处理时执行的动作阶段。', 'list'],
  running: ['运行中', '工位运行检查时执行的动作阶段。', 'list'],
  collect: ['收取', '玩家收取发酵结果时执行的动作阶段。', 'list'],
  cut: ['切割', '砧板切割时执行的动作阶段。', 'list'],
  press: ['按压', '榨汁机按压时执行的动作阶段。', 'list'],
  drop_result: ['掉落产物', '完成后是否把产物直接掉落到世界，而不是仅写入内部 GUI 或容器。', 'boolean'],
  interaction_delay_ms: ['交互间隔', '同一玩家连续触发该工位交互的最小间隔，单位毫秒。', 'number'],
  tool_item_sources: ['工具来源', '识别为厨刀、锅铲等工具的 ItemSource 列表。', 'list'],
  cut_damage: ['切割伤害', '砧板切割失败或误伤时的伤害开关、概率与数值。', 'object'],
  scald_damage: ['烫伤伤害', '炒锅等热工位对玩家造成烫伤的开关与伤害值。', 'object'],
  value: ['数值', '当前条目的数值，语义由父节点决定。', 'number'],
  chance: ['概率', '触发概率，通常按百分比填写。', 'number'],
  need_bowl: ['需要碗', '出锅时是否要求玩家持有或提供碗类容器。', 'boolean'],
  stir_delay_ms: ['翻炒间隔', '两次翻炒动作之间的最小间隔，单位毫秒。', 'number'],
  timeout_ms: ['超时毫秒', '炒锅状态超过该时间未处理时按过火或失败处理。', 'number'],
  ignite_heat_source: ['点亮热源', '放入燃料或食材后是否尝试把下方热源切换为点亮外观。', 'boolean'],
  invalid_result_item_sources: ['无效产物', '未命中配方或结果无效时使用的兜底产物来源。', 'list'],
  spatula_item_sources: ['锅铲来源', '识别为锅铲的 ItemSource 列表。', 'list'],
  heat_levels: ['火候等级', '按下方热源 ItemSource 映射到的火候等级列表。', 'list'],
  stir_animation: ['翻炒动画', '翻炒时食材抛起、旋转和持续时间的动画参数。', 'object'],
  duration_ticks: ['持续 tick', '动画或运行阶段的持续时间，20 tick 约等于 1 秒。', 'number'],
  height: ['高度', '动画抛起高度或展示高度，单位方块格。', 'number'],
  rotation_axis: ['旋转轴', '动画旋转轴，可选 x、y、z。', 'enum'],
  rotation_degrees: ['旋转角度', '动画旋转角度，单位度。', 'number'],
  failure: ['失败规则', '工位处理失败时的概率、产物与反馈配置。', 'object'],
  item_sources: ['物品来源', '参与匹配、消耗、返还或产出的 ItemSource 列表。', 'list'],
  permission: ['权限', '玩家执行该配方时需要拥有的权限节点；留空表示不限制。', 'text'],
  id: ['ID', '配方唯一标识。', 'text'],
  result: ['产物', '配方完成后的产物配置。', 'object'],
  actions: ['阶段动作', '工位流程中各阶段触发的 CoreLib Action 列表。', 'object'],
  check_delay_ticks: ['检查周期', '后台运行工位的检查间隔，单位 tick。', 'number'],
  heat_item_sources: ['热源来源', '识别为热源的方块 ItemSource 列表。', 'list'],
  ingredients: ['食材列表', '炒锅配方需要的食材记录列表，包含物品来源、数量和翻炒规则。', 'list'],
  fuels: ['燃料', '可投入燃料及其燃烧时间、火力等参数列表。', 'list'],
  duration_seconds: ['持续秒数', '燃料增加的燃烧时间，单位秒。', 'number'],
  moisture_rules: ['水分规则', '可转化为水分的输入物和返还物配置。', 'list'],
  input_item_sources: ['输入来源', '触发规则所需的输入物品来源。', 'list'],
  moisture: ['水分', '增加或消耗的水分数值。', 'number'],
  reset_progress_when_steam_empty: ['蒸汽耗尽重置', '蒸汽耗尽时是否重置当前蒸制进度。', 'boolean'],
  steam_production_efficiency: ['产汽效率', '每周期最多把多少水分转换为蒸汽。', 'number'],
  steam_conversion_efficiency: ['蒸汽转进度', '每次蒸汽消耗换算成多少烹饪进度。', 'number'],
  steam_consumption_efficiency: ['蒸汽消耗', '每个周期基础蒸汽消耗量。', 'number'],
  heat: ['火力', '烤炉火力区间、衰减或燃料提供的火力。', 'object'],
  min: ['最小值', '允许推进流程的最小阈值。', 'number'],
  max: ['最大值', '允许推进流程的最大阈值。', 'number'],
  decay_per_second: ['每秒衰减', '火力每秒自然下降的数值。', 'number'],
  require_container: ['需要容器', '榨汁或收取时是否要求玩家提供容器。', 'boolean'],
  max_fluid_ml: ['最大容量 ml', '榨汁机内部流体容量上限，单位毫升。', 'number'],
  default_serving_ml: ['默认盛取 ml', '每次盛取默认消耗的流体量，单位毫升。', 'number'],
  container_item_sources: ['容器来源', '允许作为容器的 ItemSource 列表。', 'list'],
  drop_completed_result_on_break: ['破坏掉落成品', '工位被破坏时是否掉落已经完成但未取出的产物。', 'boolean'],
  pause_when_open: ['打开时暂停', 'GUI 打开时是否暂停发酵或后台处理进度。', 'boolean'],
  require_sealed: ['需要密封', '发酵桶开始或推进时是否要求处于密封状态。', 'boolean'],
  offset: ['偏移', '展示实体相对工位方块的 x/y/z 偏移。', 'object'],
  rotation: ['旋转', '展示实体的 x/y/z 旋转角度。', 'object'],
  scale: ['缩放', '展示实体的 x/y/z 缩放倍率。', 'object'],
  x: ['X', 'X 轴数值。', 'number'],
  y: ['Y', 'Y 轴数值。', 'number'],
  z: ['Z', 'Z 轴数值。', 'number']
};

const localeMessages: Record<string, string> = Object.fromEntries([
  ['emakicooking.module.name', 'Cooking'],
  ['emakicooking.module.summary', '工位、展示实体、输入规则'],
  ['emakicooking.file.config.title', '主配置'],
  ['emakicooking.file.config.comment', '烹饪系统主配置，包含工位、展示实体和输入规则。'],
  ['emakicooking.file.gui.title', 'GUI 模板'],
  ['emakicooking.file.gui.comment', '烹饪工位 GUI 模板，控制槽位、按钮和提示物品。'],
  ['emakicooking.file.recipes.title', '配方文件'],
  ['emakicooking.file.recipes.comment', '烹饪配方目录，按工位类型配置输入、时间、过程规则和产物。'],
  ['emakicooking.file.item_adjustments.title', '物品展示调整'],
  ['emakicooking.file.item_adjustments.comment', '食材展示姿态调整目录，按物品覆盖展示实体的偏移、旋转和缩放。'],
  ['emakicooking.filePath.recipes_chopping_board_example_recipe.title', '砧板配方 · example recipe'],
  ['emakicooking.filePath.recipes_chopping_board_example_recipe.comment', '砧板配方示例，展示输入、切割次数、工具损耗和产物。'],
  ['emakicooking.filePath.recipes_fermentation_barrel_example_recipe.comment', '发酵桶配方示例，展示发酵时间、早收、过时和产物。'],
  ['emakicooking.filePath.recipes_grinder_example_recipe.comment', '研磨机配方示例，展示多输入、研磨时间和结果动作。'],
  ['emakicooking.filePath.recipes_juicer_example_recipe.comment', '榨汁机配方示例，展示按压次数、流体产出和容器收集。'],
  ['emakicooking.filePath.recipes_oven_example_recipe.comment', '烤炉配方示例，展示烘烤时间、火力区间和过烤规则。'],
  ['emakicooking.filePath.recipes_steamer_chain_example_recipe.comment', '蒸锅链式配方示例，展示前置步骤、蒸汽需求和阶段产物。'],
  ['emakicooking.filePath.recipes_steamer_example_recipe.comment', '蒸锅配方示例，展示输入、所需蒸汽和产物。'],
  ['emakicooking.filePath.recipes_wok_example_recipe.comment', '炒锅配方示例，展示食材、翻炒次数、火候和失败产物。'],
  ['emakicooking.filePath.item_adjustments_minecraft_carrot.comment', '胡萝卜展示调整，覆盖食材在工位上的偏移、旋转和缩放。'],
  ['emakicooking.filePath.item_adjustments_minecraft_cooked_chicken.comment', '熟鸡肉展示调整，覆盖食材在工位上的偏移、旋转和缩放。'],

  ['emakicooking.filePath.gui_fermentation_barrel.title', '发酵桶 GUI'],
  ['emakicooking.filePath.gui_fermentation_barrel.comment', '发酵桶 GUI 模板，控制输入、燃料、状态和收取按钮。'],
  ['emakicooking.filePath.gui_juicer.comment', '榨汁机 GUI 模板，控制输入、容器、流体显示和盛取按钮。'],
  ['emakicooking.filePath.gui_oven.comment', '烤炉 GUI 模板，控制燃料、输入、火力显示和产物槽位。'],
  ['emakicooking.filePath.gui_steamer.comment', '蒸锅 GUI 模板，控制燃料、水分、蒸汽和产物槽位。'],
  ['emakicooking.file.plugin.title', '插件描述'],
  ['emakicooking.file.plugin.comment', 'plugin.yml 元数据、命令、权限和依赖声明。'],
  ['emakicooking.file.web-console.title', 'WebUIEdit 注册'],
  ['emakicooking.file.web-console.comment', '此插件暴露给 WebUIEdit 的文件分组、编辑器类型和前端扩展入口。'],

  ...fields.flatMap(([path, label, comment]) => [[`emakicooking.field.${path}`, label], [`emakicooking.comment.${path}`, comment]]),
  ...itemAdjustmentFields.flatMap(([path, label, comment]) => [[`emakicooking.field.${path}`, label], [`emakicooking.comment.${path}`, comment]]),
  ...recipeFields.flatMap(([path, label, comment]) => [[`emakicooking.field.${path}`, label], [`emakicooking.comment.${path}`, comment]]),
  ...Object.entries(fieldComments).flatMap(([key, [label, comment]]) => [[`emakicooking.field.${key}`, label], [`emakicooking.comment.${key}`, comment]])
]);

registerModuleLocale(MODULE, 'zh-CN', {
  ...localeMessages,
  'emakicooking.surface.gui': '烹饪 GUI',
  'emakicooking.option.display_entities.backend.auto': '自动选择',
  'emakicooking.option.display_entities.backend.packet_events': 'PacketEvents 虚拟实体',
  'emakicooking.option.display_entities.backend.bukkit': 'Bukkit 真实实体'
});

registerModuleLocale(MODULE, 'en-US', {
  'emakicooking.module.name': 'Cooking',
  'emakicooking.module.summary': 'Stations, display entities, and input rules',
  'emakicooking.file.config.title': 'Main Config',
  'emakicooking.file.config.comment': 'Main cooking configuration covering stations, display entities, and input rules.',
  'emakicooking.file.gui.title': 'GUI Templates',
  'emakicooking.file.gui.comment': 'Cooking station GUI templates controlling slots, buttons, and hint items.',
  'emakicooking.file.recipes.title': 'Recipe Files',
  'emakicooking.file.recipes.comment': 'Cooking recipe directory organized by station type, covering inputs, timing, process rules, and outputs.',
  'emakicooking.file.item_adjustments.title': 'Item Display Adjustments',
  'emakicooking.file.item_adjustments.comment': 'Food display adjustment directory for overriding display entity offset, rotation, and scale by item.',
  'emakicooking.filePath.recipes_chopping_board_example_recipe.title': 'Chopping Board Recipe · example recipe',
  'emakicooking.filePath.recipes_chopping_board_example_recipe.comment': 'Chopping board recipe example showing input, cut count, tool damage, and output.',
  'emakicooking.filePath.recipes_fermentation_barrel_example_recipe.comment': 'Fermentation barrel recipe example showing fermentation time, early collect, overtime, and output.',
  'emakicooking.filePath.recipes_grinder_example_recipe.comment': 'Grinder recipe example showing multi-input setup, grind time, and result actions.',
  'emakicooking.filePath.recipes_juicer_example_recipe.comment': 'Juicer recipe example showing presses, fluid output, and container collection.',
  'emakicooking.filePath.recipes_oven_example_recipe.comment': 'Oven recipe example showing bake time, heat range, and overbake rules.',
  'emakicooking.filePath.recipes_steamer_chain_example_recipe.comment': 'Steamer chain recipe example showing prerequisite steps, steam cost, and staged output.',
  'emakicooking.filePath.recipes_steamer_example_recipe.comment': 'Steamer recipe example showing input, required steam, and output.',
  'emakicooking.filePath.recipes_wok_example_recipe.comment': 'Wok recipe example showing ingredients, stir count, heat level, and failure output.',
  'emakicooking.filePath.item_adjustments_minecraft_carrot.comment': 'Carrot display adjustment overriding station offset, rotation, and scale.',
  'emakicooking.filePath.item_adjustments_minecraft_cooked_chicken.comment': 'Cooked chicken display adjustment overriding station offset, rotation, and scale.',

  'emakicooking.filePath.gui_fermentation_barrel.title': 'Fermentation Barrel GUI',
  'emakicooking.filePath.gui_fermentation_barrel.comment': 'Fermentation barrel GUI template controlling input, fuel, status, and collect buttons.',
  'emakicooking.filePath.gui_juicer.comment': 'Juicer GUI template controlling input, containers, fluid display, and serving buttons.',
  'emakicooking.filePath.gui_oven.comment': 'Oven GUI template controlling fuel, input, heat display, and output slots.',
  'emakicooking.filePath.gui_steamer.comment': 'Steamer GUI template controlling fuel, moisture, steam, and output slots.',
  'emakicooking.file.plugin.title': 'Plugin Description',
  'emakicooking.file.plugin.comment': 'plugin.yml metadata, commands, permissions, and dependency declarations.',
  'emakicooking.file.web-console.title': 'WebUIEdit Registration',
  'emakicooking.file.web-console.comment': 'File groups, editor kinds, and frontend extension entries exposed to WebUIEdit by this plugin.',

  'emakicooking.surface.gui': 'Cooking GUI',
  'emakicooking.field.input_rules': 'Input Rules',
  'emakicooking.field.display_entities': 'Display Entities',
  'emakicooking.field.display_adjustments': 'Display Adjustments',
  'emakicooking.field.stations': 'Stations',
  'emakicooking.field.only_recipe_items': 'Recipe-only Input',
  'emakicooking.field.block_item_sources': 'Block Sources',
  'emakicooking.field.interactions': 'Interactions',
  'emakicooking.field.actions': 'Actions',
  'emakicooking.field.item_sources': 'Item Sources',
  'emakicooking.option.display_entities.backend.auto': 'Auto',
  'emakicooking.option.display_entities.backend.packet_events': 'PacketEvents',
  'emakicooking.option.display_entities.backend.bukkit': 'Bukkit'
});

registerPluginConfig({
  moduleId: MODULE,
  metaFields: fields,
  fileSchemas: [
    { pathPrefix: 'recipes/', fields: recipeFields },
    { pathPrefix: 'item_adjustments/', fields: itemAdjustmentFields }
  ],
  ruleFields: fieldComments,
  rules: [
    [{ key: 'rotation_axis' }, { label: '旋转轴', comment: '旋转轴，可选 x、y、z。', type: 'enum', options: ['x', 'y', 'z'], optionLabelPrefix: 'axis' }]
  ],
  listItemSchemas: [
    ['ingredients', [
      { path: 'item_sources', label: '食材来源', comment: '可匹配该食材的 ItemSource 列表。', type: 'stringList', defaultValue: ['minecraft-carrot'] },
      { path: 'amount', label: '数量', comment: '此食材需要的数量。', type: 'number', defaultValue: 1 },
      { path: 'stir_rule', label: '翻炒规则', comment: '炒锅配方加入时机，格式为“最早-最晚”。', type: 'text', defaultValue: '1-1' }
    ]],
    ['result.outputs', outputFields],
    ['outputs', outputFields],
    ['conditions', [
      { path: 'type', label: '类型', comment: '条件类型或执行器标识。', type: 'text', defaultValue: '' },
      { path: 'expression', label: '表达式', comment: '条件表达式文本。', type: 'text', defaultValue: '' },
      { path: 'params', label: '参数', comment: '条件附加参数。', type: 'map', defaultValue: {} }
    ]],
    ['inputs', inputItemFields],
    ['stations.wok.heat_levels', [
      { path: 'item_sources', label: '热源来源', comment: '匹配该火候等级的热源 ItemSource。', type: 'stringList', defaultValue: ['minecraft-campfire'] },
      { path: 'lit_item_sources', label: '点亮来源', comment: '点亮状态下使用的热源 ItemSource。', type: 'stringList', defaultValue: [] },
      { path: 'unlit_item_sources', label: '熄灭来源', comment: '熄灭状态下使用的热源 ItemSource。', type: 'stringList', defaultValue: [] },
      { path: 'level', label: '火候等级', comment: '此热源提供的火候等级。', type: 'number', defaultValue: 1 }
    ]],
    ['stations.steamer.fuels', [
      { path: 'item_sources', label: '燃料来源', comment: '可作为蒸锅燃料的 ItemSource 列表。', type: 'stringList', defaultValue: ['minecraft-coal'] },
      { path: 'duration_seconds', label: '持续秒数', comment: '燃料增加的燃烧时间。', type: 'number', defaultValue: 30 }
    ]],
    ['stations.steamer.moisture_rules', [
      { path: 'input_item_sources', label: '输入来源', comment: '可转化为水分的输入 ItemSource。', type: 'stringList', defaultValue: ['minecraft-water_bucket'] },
      { path: 'output_item_sources', label: '返还来源', comment: '转化后返还的 ItemSource。', type: 'stringList', defaultValue: ['minecraft-bucket'] },
      { path: 'moisture', label: '水分', comment: '增加的水分数值。', type: 'number', defaultValue: 100 }
    ]],
    ['stations.oven.fuels', [
      { path: 'item_sources', label: '燃料来源', comment: '可作为烤炉燃料的 ItemSource 列表。', type: 'stringList', defaultValue: ['minecraft-coal'] },
      { path: 'duration_seconds', label: '持续秒数', comment: '燃料增加的燃烧时间。', type: 'number', defaultValue: 30 },
      { path: 'heat', label: '火力', comment: '此燃料提供的火力数值。', type: 'number', defaultValue: 20 }
    ]]
  ]
});

registerPluginGuiEditor({
  moduleId: MODULE,
  editorId: 'emakicooking:gui',
  label: copy('烹饪 GUI', 'Cooking GUI'),
  fields: [
    ['type', '槽位类型', '烹饪工位槽位语义。', 'text'],
    ['ingredient', '原料槽', '放入烹饪原料的槽位。', 'text'],
    ['result', '产物槽', '展示或取出产物的槽位。', 'text'],
    ['fuel', '燃料槽', '放入燃料的槽位。', 'text'],
    ['moisture', '水分槽', '蒸锅水分输入或展示槽位。', 'text'],
    ['container', '容器槽', '榨汁机盛取容器槽位。', 'text'],
    ['progress', '进度槽', '显示烹饪、蒸制、烘烤或发酵进度的槽位。', 'text']
  ]
});

